name: ymg
channels:
  - conda-forge
dependencies:
  - python=3.11
  - huggingface_hub[cli]
  - datasets
  - python-dotenv
  - langchain
  - langchain-community
  - langchain-openai
  - tiktoken
  - pytest
  - pip:
    - yandexcloud